# Generated by Django 4.1 on 2022-09-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturegraphics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default='1')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.AlterModelOptions(
            name='project1',
            options={'verbose_name_plural': 'Cultural History'},
        ),
        migrations.AlterModelOptions(
            name='project2',
            options={'verbose_name_plural': 'Natural History'},
        ),
        migrations.AlterModelOptions(
            name='project3',
            options={'verbose_name_plural': 'Park Information'},
        ),
        migrations.AlterModelOptions(
            name='project4',
            options={'verbose_name_plural': 'Resource Management'},
        ),
    ]
