# Generated by Django 4.1 on 2022-09-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturegraphics', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default='1'),
        ),
    ]
