# Generated by Django 4.1 on 2022-09-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturegraphics', '0003_portfolio_title_alter_portfolio_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='project_image',
            new_name='portfolio_image',
        ),
    ]
