# Generated by Django 4.1 on 2022-09-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturegraphics', '0004_category_remove_project_title_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category_slug',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
