# Generated by Django 4.1 on 2022-09-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturegraphics', '0005_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/gallery'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/portfolio'),
        ),
        migrations.AlterField(
            model_name='project1',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/project1'),
        ),
        migrations.AlterField(
            model_name='project2',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/project2'),
        ),
        migrations.AlterField(
            model_name='project3',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/project3'),
        ),
        migrations.AlterField(
            model_name='project4',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/project4'),
        ),
    ]
