# Generated by Django 4.1 on 2022-09-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturegraphics', '0005_project_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category_slug',
        ),
    ]
