# Generated by Django 4.1 on 2022-09-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturegraphics', '0006_remove_project_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_slug',
        ),
    ]
