# Generated by Django 4.1 on 2022-12-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturegraphics', '0007_alter_portfolio_options_alter_gallery_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project1',
            old_name='description',
            new_name='alt_tag',
        ),
        migrations.RenameField(
            model_name='project2',
            old_name='description',
            new_name='alt_tag',
        ),
        migrations.RenameField(
            model_name='project3',
            old_name='description',
            new_name='alt_tag',
        ),
        migrations.RenameField(
            model_name='project4',
            old_name='description',
            new_name='alt_tag',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
        migrations.AddField(
            model_name='gallery',
            name='alt_tag',
            field=models.CharField(default='Alt Tag', max_length=255, null=True),
        ),
    ]
