# Generated by Django 4.1 on 2023-01-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturegraphics', '0008_rename_description_project1_alt_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(null=True, upload_to='images/gallery'),
        ),
    ]
