# Generated by Django 4.1 on 2023-01-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturegraphics', '0009_alter_gallery_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(null=True, upload_to='images/portfolio'),
        ),
        migrations.AlterField(
            model_name='project1',
            name='project_image',
            field=models.ImageField(null=True, upload_to='images/project1'),
        ),
        migrations.AlterField(
            model_name='project2',
            name='project_image',
            field=models.ImageField(null=True, upload_to='images/project2'),
        ),
        migrations.AlterField(
            model_name='project3',
            name='project_image',
            field=models.ImageField(null=True, upload_to='images/project3'),
        ),
        migrations.AlterField(
            model_name='project4',
            name='project_image',
            field=models.ImageField(null=True, upload_to='images/project4'),
        ),
    ]
